### ISSUE TITLE
nodejs version requirement

### ISSUE THREAD

**Issue by shivamakhauri04** [michaelpradel/DeepBugs#1]
Hello 
Can you share the type_to_vector.json and node_type_to_vector.json or share idea on how to generate it.

Would be waiting for a response

Thanks and regards
Shivam

**Comment by shivamakhauri04** [comment]
Hello
Can you share the type_to_vector.json and node_type_to_vector.json or share idea on how to generate it.

Would be waiting for a response

Thanks and regards
Shivam

**Comment by michaelpradel** [comment]
I have tested with node v4.2.6. For the two missing files, I've just added them to the repository. Let me know in case you have further questions (ideally, using a separate issue for unrelated questions).

**Comment by shivamakhauri04** [comment]
Thanks Michael. You have done some awesome work!
