### ISSUE TITLE
Error: "python/BugDetection.py", line 134, in <module>  ...

### ISSUE THREAD

**Issue by kaurlakhveer5** [michaelpradel/DeepBugs#10]
I have followed all the instructions in read me file. The first part works fine where I get call_* files for training and eval. When I run the second step, below message is printed with bunch of other stuff:
Traceback (most recent call last):
  File "python/BugDetection.py", line 134, in <module>
    learning_data.pre_scan(training_data_paths, validation_data_paths)

![image](https://user-images.githubusercontent.com/33881933/80419349-d267b680-888d-11ea-90fd-67f91da3ae39.png)

**Comment by michaelpradel** [comment]
Something seems to be wrong with the calls_x2.json. Can you check that this file looks like a correct JSON file, and if it does but it still doesn't work, share (part of) this file, please?

**Comment by kaurlakhveer5** [comment]
Hi Michael! Thanks for replying! 

calls_x2 File looks good to me. Below is the screenshot
![image](https://user-images.githubusercontent.com/33881933/80553872-366aa780-8980-11ea-9d4e-22308566c25c.png)

**Comment by michaelpradel** [comment]
Can you please share the entire file, and also the calls_y2.json, so I can reproduce the problem?

**Comment by kaurlakhveer5** [comment]
[call_files.zip](https://github.com/michaelpradel/DeepBugs/files/4560170/call_files.zip)
See the attachment. Thank you for looking into it! :)

**Comment by michaelpradel** [comment]
Running your command with these files works fine with me. The reason probably is that a different default encoding is used on your machine than on mine. I've just pushed [a small change](https://github.com/michaelpradel/DeepBugs/commit/7f4f43e00cfab27733431586134bd0fd07bc5149) that may solve the problem. Can you pull, re-run your command, and let me know if works now?

**Comment by kaurlakhveer5** [comment]
Hi Michael! Thank you for making those changes! I got some warnings, otherwise, it works perfectly fine :) see the screenshot. 
![image](https://user-images.githubusercontent.com/33881933/80855225-44286300-8bf4-11ea-8055-33f58a2c6272.png)

**Comment by michaelpradel** [comment]
This looks the way it should be. Of course, if you use more training data, your accuracy will be higher.
