### ISSUE TITLE
When the 'node javascript/extractFromJS.js calls --parallel 4  .. ' command is run for the bigger corpus, multiple 'calls..' .json files get created

### ISSUE THREAD

**Issue by imanchatterjee** [michaelpradel/DeepBugs#14]
Hi 
When I run the 'node javascript/extractFromJS.js calls --parallel 4  .. ' command  for the bigger corpus for programs_eval.txt(or programs_training.txt), multiple 'calls_..' .json file get created instead of a single 'calls_..'.json file(corresponding to programs_eval.txt).
Which of these 'calls_..'.json files should I use in the next step(for training the classifier) in python?

**Comment by imanchatterjee** [comment]
Hi, are you also getting multiple training files and multiple validation files when the parsing step is run on the big corpus??? If yes, then how are you building the model using these multiple training and validation files?

**Comment by michaelpradel** [comment]
Yes, getting multiple JSON files is the expected behavior when using a larger corpus. To train and validate the model, you'll have to pass all these files to DeepBugs. Please see the command under Step 2 in the README; it uses a wildcard (*) to pass multiple files.
