### ISSUE TITLE
program transformations applied

### ISSUE THREAD

**Issue by sai-teja-ponugoti** [michaelpradel/DeepBugs#16]
I have read your paper and tried to understand how positive and negative training samples are created.

Is the transformations process available in this repo, if yes, please let me know the file names which are traversing the AST's and extracting the function calls so that the examples can be created.

**Comment by michaelpradel** [comment]
The code extraction and generation of negative examples happens in these files (for swapped calls):

- [javascript/extractorOfCalls.js](https://github.com/michaelpradel/DeepBugs/blob/master/javascript/extractorOfCalls.js) extracts information about every call in the corpus. There are similar files for the other bug patterns.
- [python/LearningDataSwappedArgs.py](https://github.com/michaelpradel/DeepBugs/blob/master/python/LearningDataSwappedArgs.py) turns the code examples into vectors and, on the way, also creates negative examples. Have a look at lines 111 to 114 for creating the negative examples. Again, there are similar files for the other bug patterns.

Let me know if this helps. If not, feel free to re-open the issue.
