### ISSUE TITLE
Some Questions

### ISSUE THREAD

**Issue by Wooza** [michaelpradel/DeepBugs#21]
Hello,

I have two questions about DeepBugs:

1. Why were the old models labelled as buggy and removed with the latest commit?
2. Is there a specific reason why the other bug detectors, especially Swapped Binary Operands, were not considered in the OOPSLA 18 paper?

Best regards
Florian

**Comment by michaelpradel** [comment]
For question 1: Something had gone wrong when training the models (not sure anymore what, too little data perhaps) and they didn't work as well as they are supposed to. Would pre-trained models simplify your task significantly? If there's enough interest, we could add proper pre-trained models again.

For question 2: We had tried a couple of different bug detectors beyond what's in the paper (as you can see in the code). The Swapped Binary Operands detector didn't work as well as the Wrong Binary Operand bug detector, and the latter also finds some real-world swapped operand bugs.
