### ISSUE TITLE
setTimeout example for Angular.js project

### ISSUE THREAD

**Issue by ramsey-coding** [michaelpradel/DeepBugs#23]
In the paper, there is a code snippet from Angular.js project, where `setTimeout` function is used incorrectly.

```
browserSingleton . startPoller (100 ,
        function (delay , fn) {
            setTimeout (delay ,fn) ;
})
```

However, I am unable to find such instance in the [Angular.js](https://github.com/angular/angular.js/) code repo.

Can you please share the link to the buggy code/commit or pull request?

**Comment by michaelpradel** [comment]
The bug is present in version 0.9.0 and also some later versions of angular.js. See [here](https://code.angularjs.org/0.9.0/angular-0.9.0.js) for a release that contains the buggy code. I'm not aware of the specific commit that removed the problem. In case you find it, please share.
