### ISSUE TITLE
Incorrect filename in the README section Embeddings for Identifiers 

### ISSUE THREAD

**Issue by dtomassi** [michaelpradel/DeepBugs#3]
Part 3 of Embeddings for Identifiers has the following command:
`python3 python/EmbeddingsLearnerWord2Vec.py token_to_number_*.json encoded_tokens_*.json`.

But when the command is ran, with the appropriate filenames for `token_to_number_*.json` and `encoded_tokens_*.json`, I get an error:
`python3: can't open file 'python/EmbeddingsLearnerWord2Vec.py': [Errno 2] No such file or directory`.

Looking in the `python` directory I see a file named: `EmbeddingLearnerWord2Vec.py` not `EmbeddingsLearnerWord2Vec.py`.

Running the command with `EmbeddingLearnerWord2Vec.py` works fine.

**Comment by michaelpradel** [comment]
Thanks for pointing this out! I just fixed it here: https://github.com/michaelpradel/DeepBugs/commit/d81c299e50b7f14689115995353d1dcf6ffc51f8
