### ISSUE TITLE
Difficulty running commands on training data corpus

### ISSUE THREAD

**Issue by jjholmes** [michaelpradel/DeepBugs#7]
Seem to have difficulty running the initial step 1 command from the Readme.md

"node javascript/extractFromJS.js idsLitsWithTokens --parallel 4 data/js/programs_50_training.txt data/js/programs_50"

With all the files correctly in place it seems to return a code of
Total number of files: 0
Left in worklist: 0. Spawning an instance.
Left in worklist: 0. Spawning an instance.
Left in worklist: 0. Spawning an instance.
Left in worklist: 0. Spawning an instance.

**Comment by michaelpradel** [comment]
From your original question (before you edited it), it looks like you've downloaded the Python corpus, but you need the JavaScript corpus. Can you double-check this, please?

**Comment by mbays** [comment]
I am working with jjholmes on this project and I have downloaded the full corpus (Java) and I have experienced the same issue as what he is getting when running the first step from the ReadMe.md

**Comment by michaelpradel** [comment]
DeepBugs is for JavaScript, not Java. Running it on the Java corpus doesn't work. (I'm closing this for now; feel free to re-open if you have further questions.)

**Comment by jjholmes** [comment]
Hey Michael, Matthew misspoke we are trying it on the JavaScript corpus set provided by yourself for training data however when attempting to run, it provides feed back of 0 calls found, I’ve tried searching for different things binops/call assignments etc but it fails to find anything for all of them !

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by michaelpradel** [comment]
The idsLitsWithTokens option is not supported anymore, and I've just removed it. If you run the command with any of the following options instead, it should extract some data:
  tokens
  calls
  callsMissingArg
  assignments
  binOps

E.g., try to run this:
node javascript/extractFromJS.js tokens --parallel 4 data/js/programs_50_training.txt data/js/programs_50

**Comment by mbays** [comment]
Hi Michael, I have tried running the above command on the changes you made however I am still getting the same error that we were originally getting:

node javascript/extractFromJS.js tokens --parallel 4 data/js/programs_50_training.txt data/js/programs_50

Total number of files: 0
Left in worklist: 0. Spawning an instance.
Left in worklist: 0. Spawning an instance.
Left in worklist: 0. Spawning an instance.
Left in worklist: 0. Spawning an instance.

**Comment by shahinrostami** [comment]
Hello @mbays @jjholmes @michaelpradel,

It's just a minor issue, I have [made a pull](https://github.com/michaelpradel/DeepBugs/pull/9) request to fix this. You're welcome to use [my fork](https://github.com/shahinrostami/DeepBugs) in the meantime.

**Comment by shahinrostami** [comment]
Hello @mbays @jjholmes @michaelpradel,

It's just a minor issue, I have [made a pull request](https://github.com/michaelpradel/DeepBugs/pull/9) to fix this. You're welcome to use [my fork](https://github.com/shahinrostami/DeepBugs) in the meantime.

**Comment by michaelpradel** [comment]
Thanks for the fix. Just merged it. I'm closing this now, assuming that the problem is resolved.
