### ISSUE TITLE
How to run each bug detector?

### ISSUE THREAD

**Issue by sunbeomso** [michaelpradel/DeepBugs#8]
Hi,
I would like to just simply try out each bug detector. But the ```README.md``` does not seem to have explanations how to run each bug detector after the learning&validation process. That is, I expect that, given a javascript file as an input, then a bug detector, as an output, may report buggy locations in the file.

Can you give me some helps?

**Comment by michaelpradel** [comment]
There currently is no easy way to run a pre-trained model in an individual file, but I agree that it would be great to have. I'll try to look into it when I find some time, but can't promise when it'll happen. Pull requests are always welcome, of course :-)

**Comment by sunbeomso** [comment]
@michaelpradel Thanks for your reply.
